name: gbx_bloc
publish_to: none
description: A new Flutter package project.
version: 0.0.2
homepage: https://github.com/GB0307/flutter_gbx

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  gbx_core:
    git:
      url: https://github.com/GB0307/flutter_gbx
      path: gbx_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  build_runner:  
  freezed: ^2.5.7
  json_serializable:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

