name: gbx_core
description: A new Flutter package project.
version: 0.0.3
homepage: https://github.com/GB0307/flutter_gbx

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  talker: ^5.1.9
  freezed_annotation: ^2.4.4
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner:  
  freezed: ^2.5.7
  json_serializable:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec